// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqPiGzJdshYdMcPG1rEcFIOPxOqxQoCmE',
    appId: '1:1065354286523:web:84b4599ef50ccd4e7d609e',
    messagingSenderId: '1065354286523',
    projectId: 'my-flutter-eb196',
    authDomain: 'my-flutter-eb196.firebaseapp.com',
    storageBucket: 'my-flutter-eb196.appspot.com',
    measurementId: 'G-W371ZMP1NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5F0YDk-N_1r6Os1EwZNgWQAu0USHAd2c',
    appId: '1:1065354286523:android:15a35910707b9e877d609e',
    messagingSenderId: '1065354286523',
    projectId: 'my-flutter-eb196',
    storageBucket: 'my-flutter-eb196.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRoECYhwm33D4uTpbi8jke427kzVlm4Gs',
    appId: '1:1065354286523:ios:1629ddae696e5a9e7d609e',
    messagingSenderId: '1065354286523',
    projectId: 'my-flutter-eb196',
    storageBucket: 'my-flutter-eb196.appspot.com',
    iosClientId: '1065354286523-ltcsb8r2m4q0pooboicgk5pq1gtashg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.submit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRoECYhwm33D4uTpbi8jke427kzVlm4Gs',
    appId: '1:1065354286523:ios:1629ddae696e5a9e7d609e',
    messagingSenderId: '1065354286523',
    projectId: 'my-flutter-eb196',
    storageBucket: 'my-flutter-eb196.appspot.com',
    iosClientId: '1065354286523-ltcsb8r2m4q0pooboicgk5pq1gtashg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.submit',
  );
}
